import type { Metadata } from "next";
import { globalStyles } from "@/stitches.config";

export const metadata: Metadata = {
  title: "KOLNECT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  globalStyles();
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
