// import './globals.css'
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { globalStyles } from "@/stitches.config";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KOLNECT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  globalStyles();
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
